version: "3.9"
services:
  azure-cognitive-service-layout:
      container_name: azure-cognitive-service-layout
      image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout
      environment:
        - EULA=accept
        - billing=https://aia-form-01.cognitiveservices.azure.com
        - apikey=5e9a528e0ce74666b200b32e837ae0de
      ports:
        - "5000:5000"
      networks:
        - ocrvnet
networks:
  ocrvnet:
    driver: bridge